include ':remoteClientLib:jni:libs:deps:FreeRDP:client:Android:Studio:freeRDPCore'
include ':remoteClientLib:jni:libs:deps:moonlight-android:app'
include ':pubkeyGenerator'
include ':bVNC'
include ':aRDP-app'
include ':remoteClientLib'
include ':native-clients-libs'
include ':common'
include ':emulatorview'
project(':emulatorview').projectDir = new File(rootDir, 'remoteClientLib/jni/libs/deps/Android-Terminal-Emulator/emulatorview/')
