package com.qihua.bVNC.ssh.libvterm;

import android.util.Log;

import java.io.IOException;
import java.io.OutputStream;

/**
 * Java-side handle to a libvterm state machine. Holds a native
 * {@code VTerm*} + {@code VTermScreen*} pointer pair, exposes
 * methods that the renderer + keyboard use to feed input and read
 * the current grid.
 *
 * <p>Threading model: libvterm itself is not thread-safe. All
 * calls into native (write / setSize / getCell / etc.) must
 * happen on a single thread — we use the SSH-Paint HandlerThread
 * for paint-driven reads, and the SSH-Connect background thread
 * for input writes. Both touch different methods on different
 * schedules, but if you ever need them on the same thread, use
 * a mutex.
 *
 * <p>Damage tracking: libvterm's
 * {@code VTermScreenCallbacks.damage} fires every time a cell
 * becomes dirty. We record the dirty row in a fixed-size ring
 * buffer (the native handle has 256 slots). Java polls via
 * {@link #pollDirty()} / {@link #takeDirtyRows(int[])}.
 */
public final class SshTermStateMachine {
    private static final String TAG = "SshTermStateMachine";

    static {
        try {
            System.loadLibrary("vterm");
            System.loadLibrary("vterm_jni");
            Log.i(TAG, "libvterm + vterm_jni loaded");
        } catch (UnsatisfiedLinkError e) {
            Log.e(TAG, "native lib load failed: " + e.getMessage());
            throw e;
        }
    }

    private long nativeHandle;
    private OutputStream outputSink;

    public SshTermStateMachine(int cols, int rows) {
        if (cols < 1 || rows < 1) {
            throw new IllegalArgumentException("cols/rows must be >= 1, got " + cols + "x" + rows);
        }
        nativeHandle = nativeCreate(cols, rows);
        if (nativeHandle == 0) {
            throw new OutOfMemoryError("vterm_create failed for " + cols + "x" + rows);
        }
    }

    public void setSize(int cols, int rows) {
        if (cols < 1 || rows < 1) {
            throw new IllegalArgumentException("cols/rows must be >= 1, got " + cols + "x" + rows);
        }
        synchronized (this) {
            nativeSetSize(nativeHandle, cols, rows);
        }
    }

    /**
     * Push the AppCompat day/night theme's default fg/bg to libvterm
     * so {@link #nativeGetCell} returns the right ARGB when a cell
     * uses the terminal's default colour. The values are stored as
     * globals in vterm_jni.c and apply to all subsequent
     * nativeGetCell calls (no per-handle state). The caller
     * (SshTerminalRenderer.applyTheme) re-invokes this whenever
     * the activity's night mode flips.
     */
    public void setDefaultColors(int fgArgb, int bgArgb) {
        nativeSetDefaultColors(nativeHandle, fgArgb, bgArgb);
    }

    /**
     * Push the AppCompat day/night theme's 16-colour ANSI palette to
     * libvterm so indexed cells (\e[31m red etc.) render in the new
     * theme's red/green/etc. instead of libvterm's hardcoded
     * Solarized fallback. Length must be exactly 16 — order is
     * black, red, green, yellow, blue, magenta, cyan, white,
     * brightBlack, brightRed, ..., brightWhite.
     */
    public void setPalette(int[] palette) {
        if (palette == null || palette.length < 16) return;
        nativeSetPalette(palette);
    }

    public int getCols() {
        synchronized (this) {
            return nativeGetCols(nativeHandle);
        }
    }

    public int getRows() {
        synchronized (this) {
            return nativeGetRows(nativeHandle);
        }
    }

    /** Feed SSH bytes into the terminal state machine. */
    public void write(byte[] data, int offset, int len) {
        if (len <= 0) return;
        byte[] out;
        synchronized (this) {
            nativeWrite(nativeHandle, data, offset, len);
            // Drain any output libvterm generated in response (e.g. replies to
            // terminal queries) and forward it to the SSH channel's stdin.
            out = nativeDrainOutput(nativeHandle);
        }
        if (out != null && out.length > 0 && outputSink != null) {
            try {
                outputSink.write(out);
                outputSink.flush();
            } catch (IOException e) {
                Log.w(TAG, "write: failed to forward terminal output", e);
            }
        }
    }

    /**
     * Set the stream where terminal input bytes (generated by libvterm
     * from codepoints) are written. This is the SSH channel's stdin.
     */
    public void setOutputStream(OutputStream out) {
        this.outputSink = out;
    }

    /** Feed a single Unicode codepoint as if the user typed it (no mods). */
    public void writeInput(int codepoint) {
        writeInput(codepoint, MOD_NONE);
    }

    /**
     * Feed a Unicode codepoint with modifier state. libvterm applies CTRL
     * via {@code c &= 0x1f} (Ctrl+R → 0x12, Ctrl+C → 0x03) and ALT as an
     * ESC prefix. Use this for Ctrl+/Alt+letter combos — Android's
     * {@code getUnicodeChar()} does NOT map Ctrl+letter to control chars,
     * so the caller must strip CTRL/ALT from the meta used to fetch the
     * codepoint and pass them here instead.
     */
    public void writeInput(int codepoint, int mods) {
        byte[] out;
        synchronized (this) {
            out = nativeWriteInput(nativeHandle, codepoint, mods);
        }
        if (out != null && out.length > 0 && outputSink != null) {
            try {
                outputSink.write(out);
                outputSink.flush();
            } catch (IOException e) {
                Log.w(TAG, "writeInput: failed to write to SSH stdin", e);
            }
        }
    }

    /**
     * Feed a special key (arrows, Home/End, PageUp/Down, Insert/Delete,
     * F-keys, keypad). Goes through libvterm's {@code vterm_keyboard_key}
     * so the byte sequence matches the terminal's current cursor-key mode
     * (application vs normal) — required for zsh's mode-dependent key
     * bindings (e.g. right-arrow "accept suggestion") to fire. Use the
     * {@code KEY_*} / {@code MOD_*} constants below.
     */
    public void writeKey(int vtermKey, int mods) {
        byte[] out;
        synchronized (this) {
            out = nativeWriteKey(nativeHandle, vtermKey, mods);
        }
        if (out != null && out.length > 0 && outputSink != null) {
            try {
                outputSink.write(out);
                outputSink.flush();
            } catch (IOException e) {
                Log.w(TAG, "writeKey: failed to write to SSH stdin", e);
            }
        }
    }

    // --- VTermKey constants (mirror vterm_keycodes.h VTermKey enum) ---
    public static final int KEY_NONE      = 0;
    public static final int KEY_ENTER     = 1;
    public static final int KEY_TAB       = 2;
    public static final int KEY_BACKSPACE = 3;
    public static final int KEY_ESCAPE    = 4;
    public static final int KEY_UP        = 5;
    public static final int KEY_DOWN      = 6;
    public static final int KEY_LEFT      = 7;
    public static final int KEY_RIGHT     = 8;
    public static final int KEY_INS       = 9;
    public static final int KEY_DEL       = 10;
    public static final int KEY_HOME      = 11;
    public static final int KEY_END       = 12;
    public static final int KEY_PAGEUP    = 13;
    public static final int KEY_PAGEDOWN  = 14;
    public static final int KEY_FUNCTION_0 = 256;  // F1 = KEY_FUNCTION(1)

    /** F-key index (1..12) → VTERM_KEY_FUNCTION(n). */
    public static int keyFunction(int n) { return KEY_FUNCTION_0 + n; }

    // --- VTermModifier bitmask (mirror vterm_keycodes.h) ---
    public static final int MOD_NONE  = 0x00;
    public static final int MOD_SHIFT = 0x01;
    public static final int MOD_ALT   = 0x02;
    public static final int MOD_CTRL  = 0x04;

    /** True if any row is dirty since the last {@link #takeDirtyRows}. */
    public boolean pollDirty() {
        synchronized (this) {
            return nativePollDirty(nativeHandle);
        }
    }

    /**
     * Drain all dirty rows into {@code outRows}. Returns the number
     * of rows written. After this call {@link #pollDirty()} returns
     * false until libvterm reports new damage.
     */
    public int takeDirtyRows(int[] outRows) {
        synchronized (this) {
            return nativeTakeDirtyRows(nativeHandle, outRows);
        }
    }

    /** Read the cell at (row, col). */
    public TermCell getCell(int row, int col) {
        synchronized (this) {
            return nativeGetCell(nativeHandle, row, col);
        }
    }

    /** Read cursor position + visibility. */
    public CursorInfo getCursor() {
        synchronized (this) {
            return nativeGetCursor(nativeHandle);
        }
    }

    /**
     * Roll the libvterm viewport up by {@code rows} rows. After this
     * call, the top {@code rows} rows of the viewport contain garbage
     * (libvterm 0.3.3's internal buffer is exactly the viewport size
     * and does not retain scrolled-off content). {@link
     * SshTerminalRenderer#renderInto} paints those rows as BG so the
     * user sees a clean "scrollback" header instead of garbage chars.
     * No-op if rows <= 0 or the state machine hasn't opened yet.
     */
    public void scrollUp(int rows) {
        if (rows <= 0) return;
        synchronized (this) {
            nativeScrollUp(nativeHandle, rows);
        }
    }

    /**
     * Roll the libvterm viewport down by {@code rows} rows. Symmetric
     * to {@link #scrollUp}; the top {@code rows} rows again become
     * garbage that renderInto paints as BG. Used to walk back from
     * scrollback toward the live screen — the user must accept the
     * BG header until the remote shell redraws those rows itself.
     */
    public void scrollDown(int rows) {
        if (rows <= 0) return;
        synchronized (this) {
            nativeScrollDown(nativeHandle, rows);
        }
    }

    public void destroy() {
        synchronized (this) {
            if (nativeHandle != 0) {
                nativeDestroy(nativeHandle);
                nativeHandle = 0;
            }
        }
    }

    @Override
    protected void finalize() throws Throwable {
        try {
            if (nativeHandle != 0) {
                Log.w(TAG, "finalize: native handle leaked, destroying");
                destroy();
            }
        } finally {
            super.finalize();
        }
    }

    /**
     * One grid cell. Fields:
     * <ul>
     *   <li>{@code codepoint} — 0 means empty cell, otherwise the
     *       Unicode codepoint painted there.
     *   <li>{@code width} — 0/1/2. libvterm's reported width; 2 means
     *       a double-width CJK character (occupies two columns).
     *   <li>{@code fg} / {@code bg} — packed 0xRRGGBB (alpha
     *       implicit 0xFF). Default fg/bg are Solarized base0/base03
     *       if the cell has no explicit color.
     *   <li>{@code attrs} — bitmask: bit 0 = bold, bit 1 = italic,
     *       bit 2 = underline, bit 3 = reverse, bit 4 = blink.
     * </ul>
     */
    public static final class TermCell {
        public int codepoint;
        public int width;
        public int fg;
        public int bg;
        public int attrs;
    }

    public static final class CursorInfo {
        public int row;
        public int col;
        public boolean visible;
    }

    private static native long  nativeCreate(int cols, int rows);
    private static native void  nativeSetSize(long h, int cols, int rows);
    private static native int   nativeGetCols(long h);
    private static native int   nativeGetRows(long h);
    private static native void  nativeWrite(long h, byte[] data, int off, int len);
    private static native byte[] nativeWriteInput(long h, int codepoint, int mods);
    private static native byte[] nativeWriteKey(long h, int key, int mods);
    private static native byte[] nativeDrainOutput(long h);
    private static native boolean nativePollDirty(long h);
    private static native int   nativeTakeDirtyRows(long h, int[] outRows);
    private static native TermCell  nativeGetCell(long h, int row, int col);
    private static native CursorInfo nativeGetCursor(long h);
    private static native void  nativeScrollUp(long h, int rows);
    private static native void  nativeScrollDown(long h, int rows);
    private static native void  nativeDestroy(long h);
    private static native void  nativeSetDefaultColors(long h, int fgArgb, int bgArgb);
    private static native void  nativeSetPalette(int[] palette);
}
